---
language: ruby
rvm:
- 2.2.5

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

install:
  - bundle install
  - sudo pip install pytest

script:
  - jekyll build
  - htmlproofer ./_site --allow-hash-href --internal-domains napalm-automation.net --http-status-ignore 999 --check-html
  - cp _site-validation/site-validation.md _pages
  - jekyll build
  - pytest

after_success:
  - make purge
